apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: h67dg#LC
  my.cnf: |-
    [mysqld]
    skip-name-resolve
    symbolic-links=0
    character-set-server=utf8
    max_connections=16000
    sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    
    slow_query_log = ON
    slow_query_log_file = /var/lib/mysql/data/slow.log
    long_query_time = 1

    [client]
    default-character-set = utf8

    [mysql]
    default-character-set = utf8
kind: ConfigMap
metadata:
  name: mysql-config
